//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagBot_FFXIV_v02.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagBot_FFXIV_v02.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExpFarming_RecordWaypoint_Error {
            get {
                return ResourceManager.GetString("ExpFarming_RecordWaypoint_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point too close to one of the other points..
        /// </summary>
        internal static string ExpFarming_RecordWaypoint_Point_too_close_to_one_of_the_other_points_ {
            get {
                return ResourceManager.GetString("ExpFarming_RecordWaypoint_Point_too_close_to_one_of_the_other_points_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (.xml)|*.xml.
        /// </summary>
        internal static string MainForm_btLoadRoutes_Click_XML_Files___xml____xml {
            get {
                return ResourceManager.GetString("MainForm_btLoadRoutes_Click_XML_Files___xml____xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MainForm_btSaveRoutes_Click_Save {
            get {
                return ResourceManager.GetString("MainForm_btSaveRoutes_Click_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string MainForm_btSaveRoutes_Click_XML_files____xml____xml {
            get {
                return ResourceManager.GetString("MainForm_btSaveRoutes_Click_XML_files____xml____xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RouteManager_RouteManager_Error {
            get {
                return ResourceManager.GetString("RouteManager_RouteManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found....
        /// </summary>
        internal static string RouteManager_RouteManager_File_not_found___ {
            get {
                return ResourceManager.GetString("RouteManager_RouteManager_File_not_found___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not found. File not saved....
        /// </summary>
        internal static string RouteManager_Save__not_found__File_not_saved___ {
            get {
                return ResourceManager.GetString("RouteManager_Save__not_found__File_not_saved___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saved.
        /// </summary>
        internal static string RouteManager_Save_File_Saved {
            get {
                return ResourceManager.GetString("RouteManager_Save_File_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved as: .
        /// </summary>
        internal static string RouteManager_Save_Saved_as__ {
            get {
                return ResourceManager.GetString("RouteManager_Save_Saved_as__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SittingCat_Resized {
            get {
                object obj = ResourceManager.GetObject("SittingCat_Resized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
